runtime: python39

entrypoint: gunicorn -b :$PORT app:app --timeout 120

handlers:
  - url: /.*
    script: auto

env_variables:
  FLASK_APP: app.py
  FLASK_ENV: production

instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  min_instances: 1
  max_instances: 5